### ISSUE TITLE
Clicking checkbox label in 'view' mode modifies session data

### ISSUE THREAD

**Issue by benburton** [PieElements/corespring-pie-multiple-choice#3]
Steps to reproduce:

1. Launch the demonstration using the directions from the [project readme](https://github.com/PieElements/corespring-pie-multiple-choice/blob/develop/README.md).
2. Navigate to http://localhost:5000
3. Click the "view" radio button at the top of the page.
4. Click a label for any of the choices (e.g., "Apple")

Expected behavior: The checkbox remains unchecked, as "view" mode disables modification of the collected data.
Actual behavior: The checkbox becomes checked, and the session (displayed to the right) is modified.

**Comment by edeustace** [comment]
see: https://github.com/PieLabs/corespring-multiple-choice/issues/1

**Comment by edeustace** [comment]
This is actually an issue in [corespring-choice-button](github.com/PieLabs/corespring-choice-button) that has been fixed in `#master` and `v1.0.0`.

**Comment by benburton** [comment]
:+1:
